// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using System.Xml.Schema;
namespace WofSchemaTest
{
    /// <summary>
    ///This is a test class for WaterOneFlow.Schema.GetSchema and is intended
    ///to contain all WaterOneFlow.Schema.GetSchema Unit Tests
    ///</summary>
    [TestClass()]
    public class GetSchemaTest
    {


        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }
        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion


        /// <summary>
        ///A test for SchemaV1_0 ()
        ///</summary>
        [TestMethod()]
        public void SchemaV1_0Test()
        {
            XmlSchema expected = null;
            XmlSchema actual;

            actual = WaterOneFlow.Schema.GetSchema.SchemaV1_0();

            Assert.AreEqual(expected, actual, "WaterOneFlow.Schema.GetSchema.SchemaV1_0 did not return the expected value.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for SchemaV1_1 ()
        ///</summary>
        [TestMethod()]
        public void SchemaV1_1Test()
        {
            XmlSchema expected = null;
            XmlSchema actual;

            actual = WaterOneFlow.Schema.GetSchema.SchemaV1_1();

            Assert.AreEqual(expected, actual, "WaterOneFlow.Schema.GetSchema.SchemaV1_1 did not return the expected value.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for SchemaV2_0 ()
        ///</summary>
        [TestMethod()]
        public void SchemaV2_0Test()
        {
            XmlSchema expected = null;
            XmlSchema actual;

            actual = WaterOneFlow.Schema.GetSchema.SchemaV2_0();

            Assert.AreEqual(expected, actual, "WaterOneFlow.Schema.GetSchema.SchemaV2_0 did not return the expected value.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for SchemaXmlV1_0 ()
        ///</summary>
        [TestMethod()]
        public void SchemaXmlV1_0Test()
        {
            string expected = null;
            string actual;

            actual = WaterOneFlow.Schema.GetSchema.SchemaXmlV1_0();

            Assert.AreEqual(expected, actual, "WaterOneFlow.Schema.GetSchema.SchemaXmlV1_0 did not return the expected value.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for SchemaXmlV1_1 ()
        ///</summary>
        [TestMethod()]
        public void SchemaXmlV1_1Test()
        {
            string expected = null;
            string actual;

            actual = WaterOneFlow.Schema.GetSchema.SchemaXmlV1_1();

            Assert.AreEqual(expected, actual, "WaterOneFlow.Schema.GetSchema.SchemaXmlV1_1 did not return the expected value.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

        /// <summary>
        ///A test for SchemaXmlV2_0 ()
        ///</summary>
        [TestMethod()]
        public void SchemaXmlV2_0Test()
        {
            string expected = null;
            string actual;

            actual = WaterOneFlow.Schema.GetSchema.SchemaXmlV2_0();

            Assert.AreEqual(expected, actual, "WaterOneFlow.Schema.GetSchema.SchemaXmlV2_0 did not return the expected value.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }

    }


}
