ALTER TABLE [dbo].[Sites_stage]
    ADD CONSTRAINT [unique_sitecode_network_code_stage] UNIQUE NONCLUSTERED ([SiteCode] ASC, [NetworkID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

