CREATE TABLE [dbo].[odm_dv_variables] (
    [VariableID]                INT            NOT NULL,
    [VariableCode]              NVARCHAR (110) NULL,
    [VariableName]              NVARCHAR (200) NULL,
    [SampleMedium]              NVARCHAR (50)  NULL,
    [ValueType]                 VARCHAR (17)   NOT NULL,
    [isRegular]                 BIT            NULL,
    [TimeSupport]               VARCHAR (1)    NOT NULL,
    [TimeUnitsID]               VARCHAR (3)    NOT NULL,
    [GeneralCategory]           NVARCHAR (50)  NULL,
    [NoDataValue]               FLOAT          NULL,
    [networkId]                 INT            NULL,
    [VariableUnitsID]           INT            NULL,
    [mediumCode]                NCHAR (10)     NULL,
    [stat_cd]                   VARCHAR (8)    NULL,
    [DataType]                  NVARCHAR (50)  NULL,
    [TimeUnitsAbbreviation]     VARCHAR (1)    NOT NULL,
    [TimeUnitsName]             VARCHAR (3)    NOT NULL,
    [VariableVocabulary]        VARCHAR (6)    NOT NULL,
    [hs_variableCode]           NVARCHAR (55)  NULL,
    [hs_newVariableCode]        NVARCHAR (110) NULL,
    [VariableUnitsAbbreviation] NVARCHAR (50)  NULL,
    [VariableUnitsName]         NVARCHAR (50)  NULL,
    [VariableUnitsType]         NVARCHAR (50)  NULL,
    [parm_cd]                   VARCHAR (8)    NULL
);

