CREATE TABLE [dbo].[odm_dv_series] (
    [siteID]                    VARCHAR (16)   NULL,
    [usgs_agency]               VARCHAR (8)    NULL,
    [SiteCode]                  VARCHAR (32)   NULL,
    [siteName]                  VARCHAR (100)  NULL,
    [TimeSupport]               INT            NOT NULL,
    [TimeUnitsId]               INT            NOT NULL,
    [TimeUnitsName]             VARCHAR (3)    NOT NULL,
    [MethodName]                VARCHAR (255)  NULL,
    [MethodID]                  INT            NULL,
    [SourceID]                  INT            NOT NULL,
    [Organization]              VARCHAR (4)    NOT NULL,
    [SourceDescription]         VARCHAR (22)   NOT NULL,
    [QualityControlLevelID]     INT            NULL,
    [EndDateTime]               DATETIME       NULL,
    [usgs_stat_cd]              VARCHAR (8)    NULL,
    [VariableName]              NVARCHAR (200) NULL,
    [SampleMedium]              NVARCHAR (50)  NULL,
    [ValueType]                 VARCHAR (17)   NOT NULL,
    [isRegular]                 BIT            NULL,
    [GeneralCategory]           NVARCHAR (50)  NULL,
    [NoDataValue]               FLOAT          NULL,
    [VariableUnitsID]           INT            NULL,
    [DataType]                  NVARCHAR (50)  NULL,
    [VariableVocabulary]        VARCHAR (6)    NOT NULL,
    [SiteVocabulary]            VARCHAR (6)    NOT NULL,
    [hs_siteCode]               VARCHAR (21)   NULL,
    [ws_siteCode]               VARCHAR (23)   NULL,
    [TimeUnitsAbbreviation]     VARCHAR (1)    NOT NULL,
    [VariableCode]              NVARCHAR (110) NULL,
    [usgs_parm_cd]              VARCHAR (8)    NULL,
    [VariableUnitsAbbreviation] NVARCHAR (50)  NULL,
    [VariableUnitsName]         NVARCHAR (50)  NULL,
    [VariableUnitsType]         NVARCHAR (50)  NULL,
    [beginDateTime]             DATETIME       NULL,
    [ValueCount]                INT            NULL
);

