CREATE NONCLUSTERED INDEX [ix_parm]
    ON [dbo].[series]([parm_cd] ASC)
    INCLUDE([stat_cd], [loc_web_ds], [medium_grp_cd]) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

