CREATE NONCLUSTERED INDEX [ix_parm_qw]
    ON [dbo].[series]([parm_cd] ASC)
    INCLUDE([medium_grp_cd]) WHERE ([data_type_cd]='qw') WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

