CREATE NONCLUSTERED INDEX [ix_varaible_loc]
    ON [dbo].[series]([data_type_cd] ASC, [parm_cd] ASC, [stat_cd] ASC, [loc_web_ds] ASC, [dd_nu] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

