CREATE NONCLUSTERED INDEX [site_no]
    ON [dbo].[USGS_sitefile]([site_no] ASC)
    INCLUDE([agency_cd], [station_nm]) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

